# Generated by Django 5.0.2 on 2024-03-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_group_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_students_in_group',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='min_students_in_group',
            field=models.IntegerField(default=1),
        ),
    ]
